################ English Language ##################
[en]
languageName = "English"
languageCode = "en-us"
contentDir = "content/english"
weight = 1

################ Indonesian Language ##################
[id]
languageName = "Bahasa Indonesia"
languageCode = "id-id"
contentDir = "content/indonesian"
weight = 2
